project_id = "cxkvyrtdgbqxtcelytwl"

[functions.send-vendor-invite]
verify_jwt = false

[functions.create-gelato-order]
verify_jwt = true

[functions.farmers-market-search]
verify_jwt = false

[functions.get-distance]
verify_jwt = false

[functions.get-payment-method-details]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false